project_id = "mqaplaplgfcbaaafylpf"

[functions.notification-cron-worker]
verify_jwt = false

[functions.notification-retry-worker]
verify_jwt = false

[functions.dispatch-notification]
verify_jwt = false

[functions.notifications-test]
verify_jwt = false

# DEPRECATED: Use payments-api instead
# [functions.provider-subscription]
# verify_jwt = true

[functions.create-customer-setup-intent]
verify_jwt = true

[functions.create-job-payment-intent]
verify_jwt = true

[functions.get-or-create-referral-profile]
verify_jwt = false

[functions.register-referral-signup]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.subscribe-push]
verify_jwt = true

[functions.unsubscribe-push]
verify_jwt = true

[functions.purchase-webhook]
verify_jwt = false

[functions.lookup-home]
verify_jwt = false

[functions.pricing-engine]
verify_jwt = false

[functions.price-service]
verify_jwt = false

[functions.assistant]
verify_jwt = true

[functions.assistant-provider]
verify_jwt = true

[functions.stripe-connect]
verify_jwt = false

[functions.payments-api]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.payments-ai]
verify_jwt = true

[functions.import-clients]
verify_jwt = true

[functions.chat-ai]
verify_jwt = true

[functions.issue-referral-reward]
verify_jwt = true

[functions.push-on-message]
verify_jwt = true

[functions.get-stripe-config]
verify_jwt = false

[functions.stripe-health]
verify_jwt = false

[functions.generate-maintenance-reminders]
verify_jwt = false

[functions.send-service-followups]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = true

[functions.send-appointment-reminders]
verify_jwt = false

[functions.short-links-api]
verify_jwt = true

[functions.generate-qr-code]
verify_jwt = true

[functions.short-link-redirect]
verify_jwt = false

[functions.get-homeowner-insights]
verify_jwt = true

[functions.auto-renew-subscriptions]
verify_jwt = false

[functions.pricing-engine]
verify_jwt = false

[functions.notifications-health]
verify_jwt = false